site_url: https://pixxelstorm.pages.dev
display_url: https://pixxelstorm.pages.dev

backend:
  name: github
  repo: lalits1219/pixxelstorm
  branch: main
  auth_type: implicit
  client_id: Ov23liCkDu9J8sjfHN1I
  
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "airdrops"
    label: "Airdrops"
    folder: "src/data/airdrops"
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["LIVE", "UPCOMING", "ENDED"] }
      - { label: "Description", name: "description", widget: "text" }

  - name: "news"
    label: "News"
    folder: "src/data/news"
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
